# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder "./..", "/vagrant"
  config.vm.provider :virtualbox do |v|
     v.customize ["modifyvm", :id, "--memory", 1048, "--natdnshostresolver1", "on"]
     v.name = "p4helper"
  end

  config.vm.provision :shell, path: "provision.sh"
end
